FROM node:12.19.0-alpine3.9 AS build-stage
LABEL MAINTAINER=victormagalhaessales@gmail.com

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install -g @nestjs/cli@7.5.6
RUN npm install

COPY . .

RUN npm run build

FROM node:12.19.0-alpine3.9 as prod-stage
LABEL MAINTAINER=victormagalhaessales@gmail.com

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY --from=build-stage /usr/src/app/dist ./dist

EXPOSE 3000

CMD ["node", "dist/main"]